title: "Pluk & Deel"
description: "Appels plukken in Zweeloo en Aalden (Drenthe). Zelf jam maken, samen helpen, opbrengst naar lokale doelen."
url: "https://plukendeel.github.io"
baseurl: "/Pluk-en-Deel-2"
lang: nl

# Social & Contact
facebook: "https://www.facebook.com/share/1JrC9K9QGv"
email: "plukendeel@gmail.com"
phone: "+31645288841"
address: "Zweeloo en Aalden, Drenthe, Nederland"
# Netlify CMS
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
plugins:
  - jekyll-relative-links
  - jekyll-sitemap
